### ISSUE TITLE
Sorry, this feature is not ready yet ...

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/avatar#1]
I created a menu link:

```
      items.push(bl('My Avatar', 'avatar', {
          attributes: {
            'data-icon': 'lock',
            'class': 'menulinks'
          },
          reloadPage:true
      }));
```

I see this message:

![edit-picture](https://cloud.githubusercontent.com/assets/13283396/16400899/beb5fe4e-3c9c-11e6-809f-43e73f97aac1.PNG)

I'm using Services 7.x-3.14 ... the latest one.

Is the latest version of drupalgap SDK required as well?

**Comment by signalpoint** [comment]
@mkinnan Editing an existing picture is not yet possible.

**Comment by mkinnan** [comment]
Hmm ... thanks!

Is this something that will be added in the near future (e.g., a week) or something down the road (e.g., a month or two)?

**Comment by signalpoint** [comment]
@mkinnan Soon-ish, within a week or two I'd say.

**Comment by mkinnan** [comment]
Any updates on this?

**Comment by mkinnan** [comment]
Checking in again ...

**Comment by signalpoint** [comment]
@mkinnan Just fixed this, grab the latest `avatar.js` for the fix, and re-read the README.
