### ISSUE TITLE
Displaying Avatar Yields 'undefined'

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/avatar#3]
In my `my_module_entity_post_render_content()` function, I am trying to display the author's avatar via:

```
theme('avatar', { account: Drupal.user });
```

It keeps displaying:

`undefined:1 GET http://example.com/undefined 404 (Not Found)`

Console.log shows I am loading **Drupal.user** correctly before trying to load the avatar.

I'm using latest jDrupal, Drupalgap SDK, Drupalgap module, and services.

**Comment by signalpoint** [comment]
@mkinnan Do you see a `picture` property in the `Drupal.user` object?

**Comment by mkinnan** [comment]
Yes ...

```
picture: "30"
```

**Comment by signalpoint** [comment]
@mkinnan Thanks for confirming. It actually should be a full picture object, instead of just the file id. I've gotten around this a few times by implementing a custom hook in _Drupal_:

```
/**
 * Implements hook_services_request_postprocess_alter().
 */
function my_module_services_request_postprocess_alter($controller, $args, &$result) {
  switch ($controller['callback']) {
    case '_system_resource_connect':
      if ($result->user->uid) {
        // Fully load the user account for DrupalGap.
        $account = user_load($result->user->uid);
        $result->user = $account;
      }
      break;
  }
}
```

**Comment by mkinnan** [comment]
That approach worked, but it is missing a bracket:

```
/**
 * Implements hook_services_request_postprocess_alter().
 */
function my_module_services_request_postprocess_alter($controller, $args, &$result) {
  switch ($controller['callback']) {
    case '_system_resource_connect':
      if ($result->user->uid) {
        // Fully load the user account for DrupalGap.
        $account = user_load($result->user->uid);
        $result->user = $account;
      }
      break;
  }
}
```

**Comment by signalpoint** [comment]
@mkinnan Thanks, I've updated the code.
